{
 "title": "HMS Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method, uri) (rate(http_server_requests_count{job=\"otel-collector\"}[1m]))"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method, uri) (rate(http_server_requests_sum{job=\"otel-collector\"}[1m])) / sum by(method, uri) (rate(http_server_requests_count{job=\"otel-collector\"}[1m]))"
    }
   ]
  },
  {
   "title": "JVM Memory Utilisation (HMS Service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "jvm_memory_used{exported_job=\"hms-service\"}"
    }
   ]
  },
  {
   "title": "JVM Memory Utilisation (HMS HR Service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "jvm_memory_used{exported_job=\"hms-hr-service\"}"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "filters": [
      { "id": "617d1402", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=~",
       "scope": "resource",
       "tag": "service.name",
       "value": [
        "hms-hr-service",
        "hms-service"
       ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}